version: "3"
db:
  image:  mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: toor
    MYSQL_DATABASE: employees
  ports:
  - "3308:3306"
  volumes:
   - ./db:/docker-entrypoint-initdb.d

web:
  image: tomcat:latest
  # Environment variables do not appear to be getting loaded the first time Tomcat starts!
  environment:
    JDBC_URL: jdbc:mysql://db1:3308/employees?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    JDBC_USER: root
    JDBC_PASS: toor
  ports:
   - "8080:8080"
  volumes:
   - /var/tmp/warfiles/target:/usr/local/tomcat/webapps
  links:
    - db:db1
